### ISSUE TITLE
New install fails to load

### ISSUE THREAD

**Issue by faktaochkunskap** [jcoppieters/cody#20]
I am testing Cody and install went smothless. 

Now I have a problem. I have started node with forever and in the web page I get error.

Cody looks for the files in /mysite/mysite/ for some unknown reason. 
 
Error: Failed to lookup view "/home/ulf/Dokument/mysite/mysite/views/index.ejs" in views directory "/home/ulf/Dokument/mysite/views"
   at EventEmitter.app.render (/home/ulf/Dokument/mysite/node_modules/cody/node_modules/express/lib/application.js:555:17)
   at ServerResponse.res.render (/home/ulf/Dokument/mysite/node_modules/cody/node_modules/express/lib/response.js:938:7)
   at Application.renderView (/home/ulf/Dokument/mysite/node_modules/cody/apps/Application.js:354:15)
   at /home/ulf/Dokument/mysite/node_modules/cody/apps/Application.js:325:12
   at Controller.doRequest (/home/ulf/Dokument/mysite/node_modules/cody/controllers/Controller.js:49:5)
   at Application.handToController (/home/ulf/Dokument/mysite/node_modules/cody/apps/Application.js:308:14)
   at Application.servePage (/home/ulf/Dokument/mysite/node_modules/cody/apps/Application.js:249:10)
   at /home/ulf/Dokument/mysite/node_modules/cody/startWebApp.js:40:15
   at Layer.handle [as handle_request] (/home/ulf/Dokument/mysite/node_modules/cody/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/ulf/Dokument/mysite/node_modules/cody/node_modules/express/lib/router/route.js:110:13)

**Comment by faktaochkunskap** [comment]
Started with node and now I see this in the console:

Template.findController -> controllerName = ContentController not found.

**Comment by faktaochkunskap** [comment]
I think the problem could be in /apps/application.js line 350 or 351.

**Comment by jcoppieters** [comment]
As it is raining in Belgium, 
I’ll do a clean install on my machine and will try to duplicate the error…

give a half an hour :-)

Johan Coppieters.

**Comment by faktaochkunskap** [comment]
Raining here also!

**Comment by jcoppieters** [comment]
OK, I found the error.
It came from a change we've made needed for the hosting setup of multiple sites.

I now changed the normal setup to resemble more like this hosting setup on our servers.
You now have a kind of "cody development directory" in which we'll install cody + 1 directory per cody project you're going to do.

Johan Coppieters.

Best would be to restart the install... sorry.
(see my clean install below)


$ cd ~
$ mkdir codydev
$ cd codydev

$ npm install cody
cody@3.3.4 node_modules/cody
├── vhost@2.0.0
├── mime@1.3.4
├── ejs@0.8.8
├── express-session@1.10.4 (utils-merge@1.0.0, cookie-signature@1.0.6, cookie@0.1.2, on-headers@1.0.0, parseurl@1.3.0, depd@1.0.0, crc@3.2.1, uid-safe@1.1.0, debug@2.1.3)
├── body-parser@1.12.2 (content-type@1.0.1, bytes@1.0.0, raw-body@1.3.3, depd@1.0.0, qs@2.4.1, iconv-lite@0.4.7, on-finished@2.2.0, debug@2.1.3, type-is@1.6.1)
├── multer@0.1.8 (qs@1.2.2, mkdirp@0.3.5, type-is@1.5.7, busboy@0.2.9)
├── nodemailer@1.3.2 (nodemailer-direct-transport@1.0.2, nodemailer-smtp-transport@1.0.2, buildmail@1.2.1, libmime@0.1.7, hyperquest@1.0.1)
├── mysql@2.6.1 (require-all@1.0.0, bignumber.js@2.0.5, readable-stream@1.1.13)
└── express@4.12.3 (merge-descriptors@1.0.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, cookie@0.1.2, range-parser@1.0.2, fresh@0.2.4, escape-html@1.0.1, content-type@1.0.1, vary@1.0.0, parseurl@1.3.0, finalhandler@0.3.4, serve-static@1.9.2, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.0, on-finished@2.2.0, qs@2.4.1, debug@2.1.3, etag@1.5.1, type-is@1.6.1, send@0.12.2, accepts@1.2.5, proxy-addr@1.0.7)

$ node ./node_modules/cody/bin/create_site
Creating cody web tree in  /Users/johan/newer
Enter sitename: newer
Note: also using $sitename as database name.
Note: by default the mysql root user has no password so you can just hit enter, if you forgot the root password http://dev.mysql.com/doc/refman/5.0/en/resetting-permissions.html
2) Enter root password for mysql so we can create a new database and user: haha
3) Enter site database user: newer
4) Enter site database password: newer
5) Enter hostname for site: localhost
Site 'newer' has been prepared.

Please create DNS entries, or add to /etc/hosts:
127.0.0.1     localhost
Also check index.js and config.json to fine-tune extra parameters, encryption key, ...
Start your site using:
forever start index.js
or
node index.js

$ node newer.js

**Comment by faktaochkunskap** [comment]
Great to hear that you solved it. 

No problem with reinstalling have done that a couple of times...

**Comment by faktaochkunskap** [comment]
Problem installning now. 

Error: ENOENT, no such file or dirrectory: /usr/local/data/iprog

**Comment by jcoppieters** [comment]
Is this windows or a unix variant?

We need a directory to store uploaded files, images, etc…
I create a directory (here “iprog”, which is the name of the project your are creating) in /usr/local/data
I’ll check the scripts, but perhaps I assume that /usr/local/data exists… (should be in node_modules/cody/bin/create_site.js)

Johan.

**Comment by faktaochkunskap** [comment]
It is Linux, Mate a Ubuntu 14.04 variant

**Comment by faktaochkunskap** [comment]
I have started from scratch three times now new db namne new folder name.

**Comment by faktaochkunskap** [comment]
I will try to create the data directory first..

**Comment by jcoppieters** [comment]
I’ve added it to the startup script.

Johan.

**Comment by faktaochkunskap** [comment]
Mysql does not use /usr/local/data in Ubuntu it is somewhere else...

**Comment by faktaochkunskap** [comment]
databses for mysql are in /var/lib/mysql

**Comment by jcoppieters** [comment]
it has nothing to do with the mysql databases.

the CMS allows you to upload files and images for use in webpages
we have to store them somewhere, so we do that in /usr/local/data/[project-name]/files and ./images

(or in another directory, configurable in cody config)

Johan.

**Comment by faktaochkunskap** [comment]
Yes, I begin to understand now.

Bad idea to store it in a folder with only root access. I run node without sudo.

I will set a folder in Documents instead.

**Comment by jcoppieters** [comment]
Yes, true, a better place is in the user directory,
we’re used to run Cody on a server (and during development)
the /usr/local/data is created with 775, so you should be able to access it.

Johan.

**Comment by faktaochkunskap** [comment]
Puh, managed to get it right now.

Yeas, but I also run the install script without sudo.

**Comment by jcoppieters** [comment]
You’re right… (no sudo)

  Any idea’s for a better place / setup are welcome

Johan.

**Comment by jcoppieters** [comment]
We'll move this to the todo list and close this issue
