### ISSUE TITLE
Use better data store than /usr/local/data

### ISSUE THREAD

**Issue by jcoppieters** [jcoppieters/cody#21]
somewhere you don't need root access.

**Comment by faktaochkunskap** [comment]
A good place in Linux/Ubuntu is anywhere under  /home/user/ where user is the name of the user.

Example with the cody data folder:

/home/billgates/cody/data

**Comment by ticup** [comment]
@jcoppieters fixed this in 59727149150598dce1c03535b7f6288548e0d909 by allowing the user to choose its data path in the create_site script. Thanks!
