### ISSUE TITLE
Files and image path is not reflected in the code responsible for the view

### ISSUE THREAD

**Issue by faktaochkunskap** [jcoppieters/cody#22]
No images is rendered and path to files is wrong.

The front page wants to show a image from: <img src="/data/images/11.jpg" alt="">.  /data/images/11.jpg

**Comment by jcoppieters** [comment]
Did you upload images first?

the empty site, is really empty…

Johan.

**Comment by faktaochkunskap** [comment]
I found out that I also had to change the path in config.js, so now upload of files and images work!

**Comment by ticup** [comment]
@faktaochkunskap Could you be more specific about what you changed in config.json and why? This can help users that bump into the same problem.
