### ISSUE TITLE
var sitename = __filename.split("/").pop().split(".")[0];

### ISSUE THREAD

**Issue by linksgo2011** [jcoppieters/cody#25]
It does not support the Windows platform

**Comment by ticup** [comment]
Ok thanks, I need to find the courage to run and debug it on a windows platform one of these days!

**Comment by Tellan** [comment]
I've tested it working with `path.sep` for platform agnostic path separators.

    var sitename = __filename.split(path.sep).pop().split(".")[0];

**Comment by jcoppieters** [comment]
I've tested it the proposed change on windows 8, seems to work fine!  Thanks Lin.
I've pushed it and will do an npm update too.
