### ISSUE TITLE
(In mysite.js at 47 line is missing a semicolon

### ISSUE THREAD

**Issue by linksgo2011** [jcoppieters/cody#26]
// 1a. load default config
cody.config = require(path.join(__dirname, sitename, "config.json"));
cody.config.controllers = cody.config.controllers || []

**Comment by ticup** [comment]
Fixed in 7af59af26cb1c9f9a08a75f155a40af25eeb4da1, thanks! ;)
(Well, it's changed in the doc/empty/index.js, so you'll only see the fix if you create a new site)
