### ISSUE TITLE
I want to add a Chinese language, how to join this project? 

### ISSUE THREAD

**Issue by linksgo2011** [jcoppieters/cody#27]
First of all, my poor English, how can I submit to the code base code
thank you

**Comment by ticup** [comment]
Hi @linksgo2011,

I'm glad you want to contribute to the project. You can find a complete guide to do a pull request [here](https://help.github.com/articles/using-pull-requests/). But I'll give you the big lines here:

I assume you have git command-line installed, if not install from [here](http://git-scm.com/downloads).

1) **Fork** this repository by clicking the "Fork" in the upper corner of this page,
or by visiting this link: https://github.com/jcoppieters/cody/fork

2) **Clone** your forked repository (probably called linksgo2011/cody) on your local computer ([guide to cloning](https://github.com/jcoppieters/cody/compare/))

````
$ git clone https://github.com/jcoppieters/cody.git
````

3) Make the changes you want to make on the files of the local repository.

4) **Commit** the changes. In your local repository do:

```` 
$ git add . -A
$ git commit -a -m "Added chinese language support"
````

5) **Push** the changes to your forked repository on github. In your local repository do:

```` 
$ git push origin master
````

3) Submit a **Pull Request** by going to your repository on github and clicking the green arrows at the left top, or by visiting this link: https://github.com/jcoppieters/cody/compare/

**Comment by ticup** [comment]
FYI, Added this explanation (and a bit more elaborately using a branch) to Contribute.md in 13abdc4b412ef41dc2c5eb52549ffc2325937a7b.

**Comment by jcoppieters** [comment]
thanks mate!

J.

**Comment by linksgo2011** [comment]
I drew some time to look at the source code, but the data is not very understanding, could you tell me can you explain the database structure and field meaning? My email is 120377843 @qq.com
![nodejs cms cody 1](https://cloud.githubusercontent.com/assets/3184441/7625625/9b5333ee-fa2c-11e4-9aa7-01fd82e5fa7e.png)
![unnamed qq screenshot20150514113311](https://cloud.githubusercontent.com/assets/3184441/7625653/08b597b0-fa2d-11e4-9b50-9cc383c7637d.png)

**Comment by jcoppieters** [comment]
1) Wow, I've had a short look at https://github.com/jcoppieters/cody/pull/30
Nice work!  If it works, we could integrate French and Dutch the same way.

**Now someone has to integrate this fork into the main branch I suppose?**

2) as for the database and program schema... I can't ofcourse understand the first flowchart...

But for the database I made a schema long time ago, it is in the documentation part of the cody website: http://www.cody-cms.org/en/schema

3) Lin, if this all works out and more people from your region get interested, perhaps we should add a 3rd language to the http://cody-cms.org website and add Chinese?  If you want to add some translations, I can copy the English content to the Chinese content and then you can change wherever you want.

Johan.

**Comment by DeanHere** [comment]
Is this still in process?

**Comment by ticup** [comment]
I have to be honest, I totally forgot about this.. Will do it tonight.

**Comment by ticup** [comment]
This was done in: https://github.com/jcoppieters/cody/pull/31

Thanks again @linksgo2011!

**Comment by linksgo2011** [comment]
ok thk

发自我的 iPhone
