### ISSUE TITLE
Proofing your About page on Cody.com

### ISSUE THREAD

**Issue by zargold** [jcoppieters/cody#34]
Proofread your About Page:

Cody is a platform created to build websites and web applications. It is multi-lingual from the ground up. (We Belgians have 3 offical languages in a country of only 10 million people!)

It is aimed at 2 target audiences: web masters and web developers.

The developers are interested because Cody is written in a modern language--JavaScript. JavaScript is a very powerful Object-Oriented language, used by Google, Microsoft and Apple to build their latest apps and servlets. It's also built on top of a modern and ultra fast webserver--Node.js. Freed from aging PHP, this ecosystem is embraced by lots of developers, even Wordpress founders have rebuilt their newest blogging platform using exactly these technologies--Node.js and JavaScript.

Web developers can easily change their (rich) content, include images and files, or add pages and subpages. It comes with a library where they can upload images and files to be used on their site. And last but not least there is a multi-language form-builder with client and server-side input validation.

Of course, Cody is built to be extendable. Developers knowing JavaScript can add their own Views, Content types, Controllers, and when needed, Models. They can build complete webapps using the same language for server and client-side programming. The resulting applications can be deployed on their own servers or hosted in the cloud.

Cody is also built for speed. Normal webpages are served without any disk IO, database access, or reading of HTML/CSS/Image files. Static file content is cached, and although there is a SQL backing store for all content and structure, most of it is read into memory at startup. Only while working in the Back-office is there any database interaction.

**Comment by ticup** [comment]
@jcoppieters Did you update this? If you did, could can you close this please? Thanks.

**Comment by jcoppieters** [comment]
Wow I missed this one!  Just made the update on the website.

many thanks to zargold !!
