### ISSUE TITLE
{ [Error: connect ECONNREFUSED] come after enter location of storing DOC.

### ISSUE THREAD

**Issue by higunjan** [jcoppieters/cody#35]
Hello I trying to do these for testing but I face issue when doing your steps. here i attached one snapshot and check out what actually it's about.

PFA
![9-30-2015 3-33-22 pm](https://cloud.githubusercontent.com/assets/6925531/10190264/06e789ce-6789-11e5-8fcb-6dd31d6c7e45.png)

**Comment by jcoppieters** [comment]
Hello,

2 questions:
- Is mySQL running?
- is the password in your config.js file in “codydev” correct?

You can verify both at the same by interactively connecting to mysql in the commandline with:
$ mysql [the database name from the config file] -u[the user from the config file] -p
[the password of the config file]

Keep us posted if you could solve the problem.

Johan.

**Comment by higunjan** [comment]
>>> is the password in your config.js file in “codydev” correct?

Where config.js is located I can't see these in my cody modules.

**Comment by jcoppieters** [comment]
When creating a project, the script asked you for a name.
A directory with this name was created.
Within this directory, you will find the file: config.json.

see screenshot below.

Johan.

**Comment by higunjan** [comment]
What should these ERROR means : Please Explain me 

![9-30-2015 3-59-18 pm](https://cloud.githubusercontent.com/assets/6925531/10190731/59921dbc-678c-11e5-9fad-da4f39f0b8f5.png)

**Comment by jcoppieters** [comment]
the "Accès refusé" is clearly "wrong password" for the user "root" on your localhost's mysql server.

**Comment by higunjan** [comment]
Yup Now all clear. Thank you! for your Effort
