### ISSUE TITLE
cant install - licence error

### ISSUE THREAD

**Issue by djholly123** [jcoppieters/cody#36]
hi

apologies if I am missing something the install instructions did not work for me on windows 10

had to clone from git then ....

D:\mc\codydev\cody>npm install
npm WARN EPACKAGEJSON cody@3.4.0 No license field.

any ideas ?

**Comment by jcoppieters** [comment]
It seems that new versions of npm enforce the use of a "licence" attribute in the package json file.

Someone should add 
  "license": "MIT"
In our package file. 

I don't have a computer here, but if someone could add it, Mark would be helped.

@Mark: can you send us the errors you get when installing (there should no need for git cloning)

Johan.

**Comment by djholly123** [comment]
thanks for reply but still a loop of problems 

initial getting of cody fails ? ...

D:\mc\codydev>npm install cody
D:\mc
└── cody@3.4.0

npm WARN ENOENT ENOENT: no such file or directory, open 'D:\mc\package.json'
npm WARN EPACKAGEJSON mc No description
npm WARN EPACKAGEJSON mc No repository field.
npm WARN EPACKAGEJSON mc No README data
npm WARN EPACKAGEJSON mc No license field.

**Comment by ticup** [comment]
I added the license to the package and update the npm version. Could you try again?

(I should get windows 10 running to test these things..)
