### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by nmpribeiro** [jcoppieters/cody#37]
Hi there,

After installing everything, I get to my 'localhost:3001' and get Cannot GET /

How can I debug it?
Thanks

**Comment by jcoppieters** [comment]
Hello,

- can you tell is what more appears in the console?
- could you also try with http://localhost:3001/en/   ?

Johan.

**Comment by nmpribeiro** [comment]
Hi @jcoppieters my first time with this :)

I got to think a little bit about it and... I needed to speciffy a valid hostname in the configuration file. It's working now:
changed "hostnames": "localhost,lavoulp", to "hostnames": "localhost,mydomain.com", on config.json

Now I have other problems, but I'll post in other threads if I can't find the reason why.
Thanks @jcoppieters
