### ISSUE TITLE
The server closed connection

### ISSUE THREAD

**Issue by nmpribeiro** [jcoppieters/cody#38]
Hi there.

So... I got to test cody and althou I can walk around for a time, this error allways happens and closes server:

`<addr>`
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/admin/nodejs/codydev/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/admin/nodejs/codydev/node_modules/cody/node_modules/mysql/lib/Connection.js:102:28)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
`<addr>`

I try to use 'node application.js' all fine until it breaks. Since I'm new to this software, perhaps you guys know better what's happening and can help me out understanting what's the problem?

Thanks in advance

**Comment by jcoppieters** [comment]
Hello,

How long is you server inactive before it happen?

We wanted to have very fast response times. So we only make 1 mysql connection when you launch the cody server.

We have seen problems with low traffic sites, where the mysql deamon disconnects from its socket connection when there is no traffic during a while.

What we did there was extend the timeout of the server.

vi /etc/my.conf
  ...
    # skip-networking  [ mysqld ]
    socket=/tmp/mysql.sock  [ everywhere ]
    wait_timeout = 31536000 
    interactive_timeout = 31536000

**Comment by nmpribeiro** [comment]
Sorry... just slipped through. Tested it, everything working fine. Quite a little powerful cms there :) congrats!
