### ISSUE TITLE
where to set/change the default mysql port

### ISSUE THREAD

**Issue by DeanHere** [jcoppieters/cody#39]
There is no mysql port setting when run the create_site script, could not connect to db because the port is wrong. And could do nothing with the script if has no root access.

**Comment by jcoppieters** [comment]
There is no setting in the config file for the mysql database server.

You are right: this should be added.
someone should submit a patch.

There are 2 places where 1 line should be added.

1) allowing to use and alternate port in the mysql.createConnection in apps/application.js

Application.prototype.getConnection = function() {
  var self = this;

  if (typeof self.connection === "undefined") {
    self.log("Application", "Make new Connection");
    
    // https://github.com/felixge/node-mysql
    self.connection = mysql.createConnection({
        host: self.dbhost,
        user: self.dbuser, password: self.dbpassword,
        database: self.db,
###
         port: self.dbport
###
    });
  } else {
    self.log("Application.getConnection", "Returning existing connection");
  }
  
  if (typeof self.connection === "undefined") {
    throw(new Error("Fatal error: No database connection"));
  }
  return self.connection;
};


2) setting the dbport to the default mysql port (I think 3306) if it is not present in the config file

  this.dbpassword = (typeof config.dbpassword === "undefined") ? "ydoc" : config.dbpassword;
###
  this.dbport = config.dbport || 3306;
###
  this.dbhost = config.dbhost || "localhost";
  this.db = config.db || "cody";

**Comment by jcoppieters** [comment]
committed to github
will be included in npm in the next code npm release

**Comment by DeanHere** [comment]
thanks
