### ISSUE TITLE
Unable to create a new site

### ISSUE THREAD

**Issue by dibosh** [jcoppieters/cody#41]
I was following the guidelines from here: http://cody-cms.org/en/install
Each time am trying to use `create_site.js` I am getting this error in the last step:
```
Creating project in  /Users/newscred/projects/personal/portfolio-ideations/portfolio-cody/

1) Enter projectname: pfoliocms
Note: also using pfoliocms as database name.
Note: by default the mysql root user has no password so you can just hit enter, if you forgot the root password http://dev.mysql.com/doc/refman/5.0/en/resetting-permissions.html

2) Enter root password for mysql so we can create a new database and user:

3) Enter site database user: admin

4) Enter site database password: mypassword

5) Enter hostname for site: pfoliocms.local

6) Enter a location for storing documents: ../../../../codydata

/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

Error: ENOENT: no such file or directory, scandir '/Users/newscred/projects/personal/portfolio-ideations/portfolio-cody/node_modules/cody/doc/empty'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Query._callback (/Users/newscred/node_modules/cody/bin/create_site.js:123:24)
    at Query.Sequence.end (/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/newscred/node_modules/cody/node_modules/mysql/lib/Connection.js:96:28)
```
Any idea?

**Comment by jcoppieters** [comment]
Hello,

I have no access to the install script here, but could it be the "-" in the directory name which is not correctly escaped in the install script?

Could you try it with a directory path without the "-" in it. That would prove my guess and we could try to fix it.

Many thanks,
Johan Coppieters, Brugge.

**Comment by dibosh** [comment]
Okay @jcoppieters I will try it now and let you know :+1:

**Comment by dibosh** [comment]
No luck :-1:  Same error:
```
6) Enter a location for storing documents: ~/codydata

/Users/newscred/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

Error: ENOENT: no such file or directory, scandir '/Users/newscred/projects/personal/personalportfolio/pfoliocodycms/node_modules/cody/doc/empty'
```

**Comment by jcoppieters** [comment]
And does the directory Users/newscred/projects/personal/personalportfolio/pfoliocodycms/node_modules/cody/doc/empty exist?

It is part of the normal npm install.

Johan Coppieters.

  (Sent from my iPhone,
   hence  the short answers)

**Comment by jcoppieters** [comment]
I had a look at the code:

The error originated from the line below in the create site script:
fs.readdirSync(codywd+"/doc/empty").forEach(....


So it seems to my the directory (/Users/newscred/projects/personal/personalportfolio/pfoliocodycms/node_modules/cody/doc/empty) is not there (npm install cody should have created it), 
or it is not accesible by the current user??

Did you install it with a different user or with the -g option?


Johan Coppieters, Brugge.

**Comment by dibosh** [comment]
Thanks @jcoppieters 
I installed it using -g option. When I tried using the `npm install` without the -g flag it didn't get installed in my current dir.

**Comment by jcoppieters** [comment]
OK, that's it!

As we serve some files from the cody directory, it can't be installed outside your working directory.
please try the  "npm install cody" from within your directory and let us know if this worked.

Johan.

**Comment by dibosh** [comment]
I will shortly and let you know.

On Mon, Mar 7, 2016 at 2:45 PM, Johan Coppieters <notifications@github.com>
wrote:

> OK, that's it!
>
> As we serve some files from the cody directory, it can't be installed
> outside your working directory.
> please try the "npm install cody" from within your directory and let us
> know if this worked.
>
> Johan.
>
> > On 06 Mar 2016, at 19:48, Md. Abdul Munim Dibosh <
> notifications@github.com> wrote:
> >
> > Thanks @jcoppieters <https://github.com/jcoppieters>
> > I installed it using -g option. When I tried using the npm install
> without the -g flag it didn't get installed in my current dir.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/jcoppieters/cody/issues/41#issuecomment-192960512>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcoppieters/cody/issues/41#issuecomment-193160146>.
>



-- 
*Md. Abdul Munim Dibosh*
Associate Product Designer
NewsCred
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2zhHjzW4X9HtM63RPb2W64k8w-56dzZqf5s-kgM02?t=http%3A%2F%2Fwww.newscred.com%2F&si=6285916075458560&pi=14e80741-0693-4e18-c3d9-e7bf9406b21a>
(M) +88*01946923667*
Twitter
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2zhHjzW4X9HtM63RPb2W64k8w-56dzZqf5s-kgM02?t=http%3A%2F%2Fwww.twitter.com%2Fnewscred&si=6285916075458560&pi=14e80741-0693-4e18-c3d9-e7bf9406b21a>
 | Blog
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2zhHjzW4X9HtM63RPb2W64k8w-56dzZqf5s-kgM02?t=http%3A%2F%2Fblog.newscred.com%2F&si=6285916075458560&pi=14e80741-0693-4e18-c3d9-e7bf9406b21a>
 | Facebook <http://www.facebook.com/newscred>

**Comment by repoissp** [comment]
Hello, 
I might have a different issue, when I install the package and then run the command  node ./node_modules/cody/bin/create_site.js

$ node ./node_modules/cody/bin/create_site.js

Creating project in  /Users/gaurrus/Sites/cody/

1) Enter projectname: mySite
Note: also using mySite as database name.
Note: by default the mysql root user has no password so you can just hit enter, if you forgot the root password http://dev.mysql.com/doc/refman/5.0/en/resetting-permissions.html

2) Enter root password for mysql so we can create a new database and user: 1234567

3) Enter site database user: mySite

4) Enter site database password: 1234567

5) Enter hostname for site: localhost

6) Enter a location for storing documents: /Users/gaurrus/Sites/cody/

mkdir /Users/gaurrus/Sites/cody/mySite/controllers
mkdir /Users/gaurrus/Sites/cody/mySite/locales
mkdir /Users/gaurrus/Sites/cody/mySite/static
mkdir /Users/gaurrus/Sites/cody/mySite/static/css
mkdir /Users/gaurrus/Sites/cody/mySite/static/images
mkdir /Users/gaurrus/Sites/cody/mySite/static/js
mkdir /Users/gaurrus/Sites/cody/mySite/views
/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
              ^
Error: ER_INVALID_DEFAULT: Invalid default value for 'created'
    at Query.Sequence._packetToError (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
    --------------------
    at Protocol._enqueue (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/gaurrus/Sites/cody/node_modules/cody/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/gaurrus/Sites/cody/node_modules/cody/bin/create_site.js:130:27
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
.
what can be wrong? thanks a lot!

**Comment by jcoppieters** [comment]
The error come from a line where we create a table with default datetime = "0000-00-00 00:00:00".
This is by default allowed (at least till mysql 5.7.x), so either you have a newer version or your installations disallowed the use of the 0000-00-00 date. see also the link below / doc of mysql.

http://stackoverflow.com/questions/25349126/how-can-i-set-the-default-value-of-a-field-as-0000-00-00-000000

**Comment by ticup** [comment]
@repoissp Thanks for letting us know.
We added this in empty.sql cdcacb3a4ae723df9cbe52fc16bdd634529420ad such that the population is executed in strict mode.
