### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by gokhandilek** [jcoppieters/cody#44]
Hi,
I was wondering if it would be possible to have user roles in this?
And do I need to use mysql? Do you have a gateway for this?

**Comment by jcoppieters** [comment]
Hi,

1) roles? no we have levels, standard only 3 are used, but you can add as many as you want, if you use them in your application. They are in the table "levels"

```
 +------+-------+
 | id   | name  |
 +------+-------+
 |    2 | user  |
 |   50 | admin |
 |   99 | super |
 +------+-------+
```

2) Yes, we use mySQL as standard DB.
we have plans to add sequelize to Cody, so you could switch database to sqlite, postgresql, sql*server, etc... but that is future work / to be done.  

of course always welcome to submit a patch  :-)

Johan.
