### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by maufarinelli** [jcoppieters/cody#45]
Hi guys, 
I am trying Cody for a small personal project. 
I am able to run the website, but unable to login in the dashboard
I am using the same user and password (codydev2) I put on the site creation, but I got login-failed
```
2) Enter root password for mysql so we can create a new database and user: root

3) Enter site database user: codydev2

4) Enter site database password: codydev2

5) Enter hostname for site: localhost

6) Enter a location for storing documents: /mysql
```
What could be the reason?

**Comment by ticup** [comment]
Hi Mauricio,

The username/password for the dashboard are different from the database. We provide some default users, you can manage them through the dashboard once logged in.

From http://www.cody-cms.org/en/install :

    the default users are: 'super', 'admin', 'test' and 'user' which all have password 'empty'

Hope that helps!


Tim.

**Comment by ticup** [comment]
Ps: the database username/password you are giving in the setup are used to create a dedicated user on the mysql database for your site. We then use this to create and manage the necessary tables (pages, users for the dashboard etc.)

**Comment by maufarinelli** [comment]
I am sorry @ticup , I could have read that part :)
Thanks a lot. It is exactly what I needed as CMS

**Comment by ticup** [comment]
Hey no worries man, I do acknowledge that our docs could be improved so ;)

Glad you like it!
