### ISSUE TITLE
How could I add a third language to my website?

### ISSUE THREAD

**Issue by maufarinelli** [jcoppieters/cody#46]
How could I add a third language to my website?
I didn't find anything about that

Thanks

**Comment by jcoppieters** [comment]
/* add the language */
insert into languages values ('pt', 'Portuguese', 0);

/* add the pages */
create table xx as select * from pages where language = 'en';
update xx set language = 'pt';
insert into pages select * from xx;
drop table xx;

/* add the content */
create table xx as select * from content where language = 'en';
update xx set language = 'pt';
insert into pages select * from xx;
drop table xx;

and restart the application, should do the trick.

**Comment by maufarinelli** [comment]
Amazing @jcoppieters 

Just to help other that try that later. To add the content,  I had to change the script to insert into content. Also, I had to change each id of the temporary table, otherwise 'ERROR: Duplicated Key 'KEY' for key 'PRIMARY'

So:
/* add the content */
create table xx as select * from content where language = 'en';
update xx set language = 'pt';
insert into **content** select * from xx;
UPDATE xx SET id=id*10 WHERE language='fr'
drop table xx;

**Comment by jcoppieters** [comment]
Hey Mauricio,

Thanks for the feedback.
I think: 

update xx set id = 0;

Would probably solve the problem too, as the id in content is auto-increment.

Johan Coppieters, Brugge.
