### ISSUE TITLE
Unable to login with default accounts

### ISSUE THREAD

**Issue by arishuynhvan** [jcoppieters/cody#49]
Hi, I've managed to set up my site with cody fully, and launched it locally:

![image](https://cloud.githubusercontent.com/assets/7850717/24402410/0bd2788a-13eb-11e7-853a-cc0f34961328.png)

However, when I tried to login using default users as suggested

> the default users are: 'super', 'admin', 'test' and 'user' which all have password 'empty'. I tried to type in 'empty' word and leave the password blank for all the default users, but to no avail

all gave me login error:

![image](https://cloud.githubusercontent.com/assets/7850717/24402548/a58fbdac-13eb-11e7-8750-76cafae4632b.png)

How may I proceed?

**Comment by ticup** [comment]
Hi Aris,

You are not accessing our server, you are accessing a jenkins server you appear to be running locally too.
By default we run on port 3000, so please try and visit localhost:3000 and try again :)

Tim.

**Comment by arishuynhvan** [comment]
THanks @ticup
