### ISSUE TITLE
what is starting uri of application

### ISSUE THREAD

**Issue by dark-coder** [jcoppieters/cody#50]

**Comment by jcoppieters** [comment]
if you run locally  -> http://localhost:3000/xx
but also "/" is redirected to the defaultLanguage.

- the 3000 = portnumber is configurable.
- the "xx" is one of the languages you support (should be in the language table)
- standard "en" is the defaultlanguage (and as we are from Belgium and speak Flemish, 
  "nl" is also in the demo setup)

you can see this in:

siteServer.all("/" + app.languages[iL].id + "/*", function (req, res) {
  app.servePage(req, res);
});
