### ISSUE TITLE
Sites down

### ISSUE THREAD

**Issue by ptums** [jcoppieters/cody#51]
Hi guys, just a heads up your main site is down and the Apache Default page is exposed.

**Comment by wxy1681** [comment]
Nobody maintains? cody is a good job. look forward to continue.

**Comment by jcoppieters** [comment]
Yes, I should maintain the server, but am off for holiday in Greece, will have access to my Mac on monday to see what happened on the server (hosted on university network)

Johan Coppieters.

  (Sent from my iPhone,
   hence  the short answers)

**Comment by wxy1681** [comment]
@jcoppieters Thank you for your contribution. I am a Linux engineer from china .If you agree ,i can mantain the site ：）

**Comment by wxy1681** [comment]
Thanks ! The site is working

**Comment by jcoppieters** [comment]
We moved the site to another server. Hopefully everything stays stable now... sorry.
