### ISSUE TITLE
error during Installation on CentOS7/virtualbox5.26

### ISSUE THREAD

**Issue by fredmj** [jcoppieters/cody#52]
Hi all,
Host=CentOS7.3
Guest=CentOS7.3/nodev8@latest/npm5.3.0/mariadb@latest

I would like to give a try to cody since it seems to be a nice CMS based on Node.JS.
I have followed the documentation as the github instructions for installation.
I have read the READM.md file
But I can't obtain a fmjconsulting.js file to use the node command.
Here the last details :
as root

> ```
> cd /var/www
> mkdir codydev && cd codydev
> npm install cody
> node ./node_modules/cody/bin/create_site
> 
> ```

Answer all the questions ...

> 
> ```
> 6) Enter a location for storing documents: /var/www/codydev/data
> 
> mkdir /var/www/codydev/fmjconsulting/controllers
> mkdir /var/www/codydev/fmjconsulting/locales
> mkdir /var/www/codydev/fmjconsulting/static
> mkdir /var/www/codydev/fmjconsulting/static/css
> mkdir /var/www/codydev/fmjconsulting/static/images
> mkdir /var/www/codydev/fmjconsulting/static/js
> mkdir /var/www/codydev/fmjconsulting/views
> created /var/www/codydev/data/fmjconsulting/
> created /var/www/codydev/data/fmjconsulting/images
> created /var/www/codydev/data/fmjconsulting/files
> ---
> Site 'fmjconsulting' has been prepared.
> 
> Please create DNS entries, or add to /etc/hosts:
> 127.0.0.1     localhost
> Also check index.js and config.json to fine-tune extra parameters, encryption key, ...
> ---
> Start your site using:
> $ forever start fmjconsulting.js
>     or
> $ node fmjconsulting.js
> -
> surf to http://localhost:3001
>     or manage your site at
> http://localhost:3001/en/dashboard
> events.js:182
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ENOENT: no such file or directory, open '/var/www/codydev/fmjconsulting/index.js'
> ```

```
[root@localhost codydev]# ll
total 32
drwxrwxrwx.  3 root root    27 18 août  17:47 data
drwxr-xr-x.  6 root root   103 18 août  17:47 fmjconsulting
-rw-r--r--.  1 root root     0 18 août  17:47 fmjconsulting.js
drwxr-xr-x. 88 root root  4096 18 août  17:45 node_modules
-rw-r--r--.  1 root root 25486 18 août  17:45 package-lock.json
```

Is someone could explain me what I'm doing wrong here?

Thanks,

**Comment by jcoppieters** [comment]
Wow 3 years ago... I suppose you didn't solve it, but just closed the issue.

**Comment by fredmj** [comment]
Yea 3 years..
No I didn't succeed at this times.
